ARG ROS_DISTRO=humble
ARG PREFIX=
ARG HUSARION_ROS_BUILD_TYPE=simulation

## =========================== ROS builder ===============================
FROM husarnet/ros:${PREFIX}${ROS_DISTRO}-ros-base AS ros_builder

ARG ROS_DISTRO
ARG PREFIX
ARG HUSARION_ROS_BUILD_TYPE

ENV HUSARION_ROS_BUILD_TYPE=${HUSARION_ROS_BUILD_TYPE}

WORKDIR /ros2_ws
RUN mkdir src

COPY src/ src/

RUN apt-get update && apt-get install -y \
        python3-pip \
        stm32flash \ 
        ros-humble-desktop


RUN vcs import src < src/rosbot/rosbot_hardware.repos && \
    vcs import src < src/rosbot/rosbot_simulation.repos  && \
    rm -rf /etc/ros/rosdep/sources.list.d/20-default.list && \
	rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO && \
    rosdep install --from-paths src --ignore-src -y

RUN MYDISTRO=${PREFIX:-ros}; MYDISTRO=${MYDISTRO//-/} && \
    source /opt/$MYDISTRO/$ROS_DISTRO/setup.bash && \
    colcon build 
